# Generated by Django 4.2.9 on 2024-02-20 05:23

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('uid', models.BigAutoField(db_column='UID', primary_key=True, serialize=False)),
                ('click_cnt', models.BigIntegerField(db_column='CLICK_CNT')),
                ('user_id', models.BigIntegerField(db_column='USER_ID', db_comment='for user table')),
            ],
            options={
                'db_table': 'click',
                'managed': False,
            },
            bases=(models.Model, API.models.CommonDateColumns),
        ),
        migrations.CreateModel(
            name='ClickTimeattack',
            fields=[
                ('uid', models.BigAutoField(db_column='UID', primary_key=True, serialize=False)),
                ('click_cnt', models.IntegerField(db_column='CLICK_CNT', db_comment='timeattack record')),
                ('user_id', models.BigIntegerField(db_column='USER_ID', db_comment='for user table')),
            ],
            options={
                'db_table': 'click_timeattack',
                'managed': False,
            },
            bases=(models.Model, API.models.CommonDateColumns),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(db_column='UID', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ID', max_length=256, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=256, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=512)),
                ('nickname', models.CharField(db_column='NICKNAME', max_length=20, null=True, unique=True)),
                ('social_idp', models.IntegerField(db_column='SOCIAL_IDP', db_comment='0=ordinary, 1=google, 2=naver, 3=kakao', default=0)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
            bases=(models.Model, API.models.CommonDateColumns),
        ),
    ]
