# Generated by Django 4.2.9 on 2024-02-21 11:59

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTimeChallenge',
            fields=[
                ('uid', models.BigAutoField(db_column='UID', primary_key=True, serialize=False)),
                ('click_cnt', models.IntegerField(db_column='CLICK_CNT', db_comment='time challenge record', default=0)),
                ('user_id', models.BigIntegerField(db_column='USER_ID')),
            ],
            options={
                'db_table': 'CLICK_TIME_CHALLENGE',
                'managed': False,
            },
            bases=(models.Model, API.models.CommonDateColumns),
        ),
        migrations.CreateModel(
            name='OauthLogin',
            fields=[
                ('uid', models.BigAutoField(db_column='UID', primary_key=True, serialize=False)),
                ('hash', models.CharField(db_column='HASH', max_length=512, null=True)),
                ('login_tf', models.BooleanField(db_column='LOGIN_TF', default=False)),
            ],
            options={
                'db_table': 'OAUTH_LOGIN',
                'managed': False,
            },
            bases=(models.Model, API.models.CommonDateColumns),
        ),
        migrations.DeleteModel(
            name='ClickTimeattack',
        ),
        migrations.AlterModelTable(
            name='click',
            table='CLICK',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
    ]
