# Generated by Django 4.2.9 on 2024-02-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_JUN', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
